### ISSUE TITLE
YoloCSharp Hakkında

### ISSUE THREAD

**Issue by kutayatik** [receptanilcengiz/recep#1]
Merhabalar, YoloCSharp Visual Studio 2017 de kullanmakta zorluk çekiyorum ve herhangi bir çözüm de bulamadım. Mail adresinizi bulamadığım için burdan yazıyorum. Yardımcı olabilir misiniz acaba?

**Comment by receptanilcengiz** [comment]
nası bir problem yaşıyorsunuz receptanilcengiz@hotmail.com

**Comment by kutayatik** [comment]
qmerkutayatik@gmail üzerinden mail attım, çok teşekkür ederim
